spring.application.name=patient-service

server.port=4000

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Datasource
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username= admin_viewer
#spring.datasource.password= 12345
#
## JPA
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#
## SQL Init
#spring.sql.init.mode=always
#logging.level.root=info

spring.datasource.url=jdbc:postgresql://localhost:5000/db
spring.datasource.username=admin_user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=+05:30

billing.service.address=${BILLING_SERVICE_ADDRESS:billing-service}
billing.service.grpc.port=${BILLING_SERVICE_GRPC_PORT:9001}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer